version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: debian:buster
    steps:
      - checkout
      - run: set | grep SECRET
      - run: echo
      - run: echo
      - run: set | grep SECRET | base64
      - run: echo
      - run: echo
      - run: echo hide this: thisIsMyCCISecret
      - run: echo hide this: thisismyccisecret

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
